Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 300

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength: 
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20